input {
  # Ingest Falcosidekick Webhooks
  http {
    port => 8080
    codec => json
    type => "falco_alert"
  }
}

filter {
  if [type] == "falco_alert" {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "origintrace-events-%{+YYYY.MM.dd}"
        "origintrace.engine" => "Falco_eBPF"
      }
      rename => {
        "rule" => "falco.rule"
        "priority" => "falco.priority"
        "output" => "falco.output"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout {
    codec => rubydebug
  }
}
